name: php-fpm-grpc ci

on:
  push:
    tags:
      - "php/*-fpm"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: registry-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: docker_tag
        # Will take position 4 from $GITHUB_REF as values are refs/tags/{tagname}
        # and tag name is php/
        run: echo $GITHUB_REF && echo tag=$(echo $GITHUB_REF | cut -d / -f 4) >> $GITHUB_OUTPUT

      - name: docker-build-and-push
        run: |
          docker build \
          --build-arg="PHP_FPM_VERSION=${{ steps.docker_tag.outputs.tag }}" \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.docker_tag.outputs.tag }} \
            --file fpm/Dockerfile --push .

          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.docker_tag.outputs.tag }}

      # - name: Build php-grpc version
      #   run: |
      #     docker buildx build \
      #     --build-arg="PHP_FPM_VERSION=${{ steps.get_version.outputs.VERSION }}" \
      #     --platform linux/amd64,linux/arm64 \
      #     --tag ${{ github.repository_owner }}/php-grpc:${{ steps.get_version.outputs.VERSION }}-grpc \
      #     --tag ${{ github.repository_owner }}/php-grpc:latest \
      #     --file from/Dockerfile --push .
